### ISSUE TITLE
Редактирование профиля

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#10]
Надо будет сделать редактирование профиля.

**Comment by Pmmlabs** [comment]
Готово https://github.com/Pmmlabs/OpenPeriscope/commit/e2e00727ef28844ce2c8f289b0f5cfe34508fc81
https://github.com/Pmmlabs/OpenPeriscope/commit/3fec62690c0f4ea63edfeca1fd65c555d84ce576

**Comment by Vol-2016** [comment]
Работает! 
(еще бы чтоб по SAVE сразу бы и обновлялось, без доп.усилий...)

Правда,  после редактирования "Name1" - шрифт строчки "Name1" стал помельче, чем "@Name2"...

**Comment by Pmmlabs** [comment]
Не понял, покажи на скриншоте

**Comment by Vol-2016** [comment]
![names](https://cloud.githubusercontent.com/assets/18728512/15194314/0900ea0a-17cb-11e6-8ae5-ebe1a8164b21.png)

**Comment by Pmmlabs** [comment]
Шрифт исправил.

**Comment by Vol-2016** [comment]
Привет.
В скрипте - не заметил когда - пропала иконка редактирования (хотя клик по месту работает):
![edit_profile](https://cloud.githubusercontent.com/assets/18728512/16710982/24a4cbbc-464e-11e6-8734-79a87b887296.png)

**Comment by Vol-2016** [comment]
Все-таки отмечу
скрипт - исчезает иконка в редакторе профиля:

![edit_profile](https://cloud.githubusercontent.com/assets/18728512/16753388/4401ff16-47f2-11e6-95a9-33d163e496b0.png)

(проверил в Хроме и Лисе; очистка кеша иногла помогает, но не надолго)
