### ISSUE TITLE
How can I enter normal Periscope username into "User" section?

### ISSUE THREAD

**Issue by paulescobar** [Pmmlabs/OpenPeriscope#108]
There is a "User" section in OpenPerisope. It shows profile for a specific user. But it does not accept normal Periscope usernames. Instead, it only accepts special hash characters to identify users.

Suppose I only have a normal Periscope username...how can I enter this into OpenPeriscope "User" section? 
Is there a way to convert normal username to special hash? 
Is there an option in OpenPeriscope to enter normal username?

**Comment by Pmmlabs** [comment]
Use "Suggested people" tab
