### ISSUE TITLE
Link to Profile

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#11]
В кнопке с птичкой не учтено, что (to Profile on Twitter) != (to Profile on Periscope) :

начиная с Periscope v.1.3.5 - в профиле можно менять  @username, 
при этом проверка на занятость - только для Перископа, для Твиттера ее нема.

**Comment by Pmmlabs** [comment]
Исправлено https://github.com/Pmmlabs/OpenPeriscope/commit/b2676b76542c2fb628aec57ab128780ad93bb7ca
