### ISSUE TITLE
Images in as userscript error

### ISSUE THREAD

**Issue by Bramengton** [Pmmlabs/OpenPeriscope#111]
When http://example.net opened in chrome/chromium or firefox it shows following like this:
![aaaaaa](https://user-images.githubusercontent.com/10059205/34247343-cb622bec-e63a-11e7-923a-c3dbe1a81a0f.png)

When clicking on the image we get an error:
> Error 401 unauthorized
> unauthorized
> 
> Guru Mediation:
> Details: cache-hhn1538-HHN 1513845482 630161982
> 
> Varnish cache server

**Comment by Pmmlabs** [comment]
Fixed
