### ISSUE TITLE
Циферки счетчиков у спойлеров в профиле

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#13]
У каждого спойлера - соответствующая циферка. Будет браться из `/user`

**Comment by Pmmlabs** [comment]
Готово https://github.com/Pmmlabs/OpenPeriscope/commit/40debdc45e27fc5c38e0d333dc711b92d31db958

**Comment by Vol-2016** [comment]
еще бы и у Blocked (в официале есть)...

**Comment by Pmmlabs** [comment]
Метод `user` такой информации не возвращает, это надо делать дополнительный запрос к API. Не хочу его делать, и так уже два дополнительных запроса делаются при заходе в профиль - список трансляций и информация по количеству зрителей. Не такая это важная информация, чтобы каждый раз загружать.
А в официальных мобильных приложениях при запуске загружаются сразу параллельно несколько (что-то около десяти) запросов, которые грузят инфу на все случаи жизни, по-моему это дичь.

**Comment by Vol-2016** [comment]
ясно
