### ISSUE TITLE
Periscope/OpenPeriscope - пропуски в "Search for people..."

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#14]
К примеру - _tram :
поиск его не видит, а он есть - 
https://www.periscope.tv/_tram

(а поправить понятно как)

**Comment by Pmmlabs** [comment]
В мобильном приложении тоже так, потому что это проблема API перископа, видимо он чистит символы при поиске. Ничем не могу помочь.

**Comment by Vol-2016** [comment]
А добавочный тест на существование соответствующей страницы 
(в случае ненахождения Поиском точного совпадения) - было бы чересчур? 
Код такой страницы содержит user_id, вполне отрабатываемый OpenPeriscope...

(ну, чтоб не полагаться на Periscope team :)

**Comment by Pmmlabs** [comment]
Функция добавлена, спасибо за репорт.
Кстати, интересное наблюдение: `_tram` не находится, но `_tran` находится, т.е. никакой обрезки символов нет, просто сам перископ что-то выводит, а что-то - нет.

**Comment by Vol-2016** [comment]
новейший Periscope v.1.4 - _tram таки находит :)

**Comment by Pmmlabs** [comment]
о, новая версия вышла. А я надеялся, что у меня будет реализован метод, не реализованный в официальном приложении...

**Comment by Pmmlabs** [comment]
_tram сейчас и так находится, без дополнительного запроса.

**Comment by Vol-2016** [comment]
> А я надеялся, что у меня будет реализован метод, не реализованный в официальном приложении..

Таки реализован! :)

В строку поиска - oniskov,
SEARCH,
и видим НАД и ПОД заголовком Search results одну и ту же фотку, -
ага, это два аккаунта одного и того же юзера, 
но только ПОД - действующий, а НАД - удаленный, несуществующий (проверь птичкой).

Сам видишь - твой метод куда как круче !
![magiclife](https://cloud.githubusercontent.com/assets/18728512/15265767/973e26bc-1996-11e6-88dc-aefcbd04bb07.png)
 :)

**Comment by Pmmlabs** [comment]
Если завтра этот аккаунт тоже начнет искаться, значит в треде разработчики перископа )

**Comment by Vol-2016** [comment]
Шоу продолжается:  после очередного обновления -
tv.periscope.android_1.4(1900221) -->  tv.periscope.android_1.4(1900222)
--  _tram  опять не виден :)

**Comment by Vol-2016** [comment]
Не проверишь мое предположение, как OpenPeriscope удается найти удаленный профиль (см. выше)?

Сначала адреса были - http://periscope.tv/user , 
потом стали  -  https://www.periscope.tv/user ,
и теперь обычный браузер в перископных ссылках автоматом меняет http на https ,
(не находя затем страничку - https://www.periscope.tv/oniskov) ,
тогда как OpenPeriscope работает с чем-то вроде http* ,
получая возможность выйти на старую базу адресов перископа, 
где и находит http://periscope.tv/oniskov ...

?

**Comment by Pmmlabs** [comment]
@Vol-2016 почему же ты думаешь, что он удаленный, если он рабочий? просто поиск его не находит. Я вообще сомневаюсь, что можно удалить свой профиль (по крайней мере я не знаю, как). http тут не при чем, я уже переделал на работу через API. Оказывается, есть метод получения пользователя по username.

**Comment by Vol-2016** [comment]
Какой же рабочий, если для браузеров  его нет в инете ? 

Как рассказал сам этот юзер -  однажды по пьяни психанул и удалил.
Kонечно, пытался у него выяснить, как удалось, без запроса в суппорт перископа - не помнит нифига.
И сейчас рабочий его акк - тот, который ПОД (см. выше).

**Comment by Pmmlabs** [comment]
В браузере нет, а API возвращает всю информацию о пользователе. Возможно, это баг перископа, который кстати свидетельствует о том, что ничего они там не удаляют, даже если говорят, что удаляют, а просто _помечают удаленным_ и не выводят при поиске. 
Про удаление - возможно, в самых ранних версиях приложения была такая возможность - не знаю, не смотрел ранние версии. А учитывая, что на iOS перископ вышел еще раньше - может, данная возможность была только в ранних версиях для iOS.

**Comment by Vol-2016** [comment]
> ничего они там не удаляют, даже если говорят, что удаляют, а просто помечают удаленным и не выводят при поиске

так это само собой.

(и там да - айфон 6С+)
