### ISSUE TITLE
Список в разделе "Карта"

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#17]
Сделать трансляции в виде списка в разделе "Карта", где-нибудь внизу, чтобы открыл город - и посмотрел сразу какие трансляции имеются.

**Comment by Vol-2016** [comment]
> чтобы открыл город - и посмотрел сразу какие трансляции имеютс

Конечно хорошо бы.

А как насчет "памяти масштаба" :
т.е. вот нашел я трансляцию на карте, довел  увеличение до нужного (скажем - дом на улице), -
так при следующем обращении к той же трансляции - увижу в том же масштабе (без повторной серии увеличений и драг-дропов карты)...

**Comment by Pmmlabs** [comment]
> при следующем обращении 

что значит обращении?

**Comment by Vol-2016** [comment]
обращение к той же трансляции (если потребуется).
---
Не помню, может повторюсь:
чтоб строчка вроде "ул.Беговая, Москва, Россия" - была и гиперссылкой на карту.

**Comment by Pmmlabs** [comment]
> повторное прослушивание-просматривание

этого всего нет, есть только чат. Можно в окне чата выводить эту самую ссылку с местоположением, которая ведет на карту.

**Comment by Pmmlabs** [comment]
Ссылка на карту теперь есть в описаниях трансляций https://github.com/Pmmlabs/OpenPeriscope/commit/113a4e51ab49637a858a6a657ee52746a7a96a41

**Comment by Vol-2016** [comment]
Что заметил:
вот текущий топ в  ru-Popular - @Kasatkin_M, 
у него 6 трансляций (все #save) - 
4 с "Россия, Москва)" и 2 с "Россия, Мытищи",
после перехода по ссылке:
на карте Москвы его трансляции обозначены (хоть и только одна),
на карте Мытищ - ни одной...

**Comment by Pmmlabs** [comment]
Я посмотрел, первые трансляции в списке (которые были сделаны вчера и сегодня), отображаются нормально, и в Москве, и в Мытищах. Старых трансляциий на карте действительно нет, ну видимо разработчики Перископа решили не захламлять карту трансляциями с #save. И еще две трансляции наложились друг на друга (видимо велись из одного места), почему-то точность координат в перископе всего 3 знака после запятой, поэтому наложения возможны.

**Comment by Pmmlabs** [comment]
Готово https://github.com/Pmmlabs/OpenPeriscope/commit/4f023ae52020dde56b3bf8d92d8dcc47229bb76d
