### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by aliasdoc** [Pmmlabs/OpenPeriscope#20]
Hi,

Since last day, "createBroadcast" path return an "Internal Server Error" (even if I try to disconnect), is the API changed ?

With official Periscope app all is functional.

```
Method: createBroadcast params: 
Object {lat: 0, lng: 0, region: "eu-central-1", width: 540, height: 960…}
cookie: "WSmDvXsiVXNlcklkIjoiMW9QRUxNT2xaQk9RZCIsIlNlc3Npb24iOiJpZEcxRHNDSFZjTFJYVVJ1bWhxNVhUYjBaOU1lbFpZbXlwV1JtQ3haczJZPSIsIlZlcnNpb24iOjF9OlKHNYOVNkfeM-t15NaM_W7EVcub5Kc9QSAtd4KZjwo="
height: 960
lat: 0
lng: 0
region: "eu-central-1"
width: 540
__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()arguments: nullassign: assign()caller: nullcreate: create()defineProperties: defineProperties()defineProperty: defineProperty()freeze: freeze()getOwnPropertyDescriptor: getOwnPropertyDescriptor()getOwnPropertyNames: getOwnPropertyNames()getOwnPropertySymbols: getOwnPropertySymbols()getPrototypeOf: getPrototypeOf()is: is()isExtensible: isExtensible()isFrozen: isFrozen()isSealed: isSealed()keys: keys()length: 1name: "Object"preventExtensions: preventExtensions()prototype: Objectseal: seal()setPrototypeOf: setPrototypeOf()__proto__: ()<function scope>hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()arguments: nullcaller: nulllength: 1name: "set __proto__"__proto__: ()<function scope> 
response: API error: 500 {"success":false,"msg":"Internal Server Error"}
```

Thanks.

**Comment by Pmmlabs** [comment]
Hi, @aliasdoc 
It is fixed already in https://github.com/Pmmlabs/OpenPeriscope/commit/cd0441084a30028e1878b3c512b98202c125cf40
However, it is not possible for now to stream a video with generated bash-script, because Periscope has turned off the rtmp-endpoints, which was used by old versions of mobile apps.

**Comment by aliasdoc** [comment]
@Pmmlabs thanks and what about new rtmp-endpoints ? If anyone had and iPhone jailbreaked you can sniff ssl traffic by overriding ssl-pinning using [ssl-kill-switch2](https://github.com/nabla-c0d3/ssl-kill-switch2) , all my devices  are not jailbreakeable (iOS 9.3.2) :(

**Comment by Pmmlabs** [comment]
New endpoints is not RTMP, it is custom protocol with custom video container. Traffic is sniffed, but nobody developed muxer for this new protocol. It is discussed in #1

**Comment by aliasdoc** [comment]
ok thanks, maybe HLS ??

**Comment by Pmmlabs** [comment]
> Now it return unauthorized 401, maybe I'm blacklisted because I make lot of live tests ...

maybe. For me it works now.
> ok thanks, maybe HLS ??

No

**Comment by fakirpic** [comment]
https://github.com/gabrielg/periscope_api/
does this work for streaming?

**Comment by Pmmlabs** [comment]
@fakirpic no. And a long time ago.
