### ISSUE TITLE
Автозакачка трансляций...

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#26]
... отслеживаемого перископера -
 о такой фиче попросили на 4pda.ru (чтоб присобачить к Periscope downloader by n3tman) -
но почему бы не добавить в OpenPeriscope (в настройки, как возможную реакцию на уведомление о LIVE) ?

**Comment by Pmmlabs** [comment]
Возможно и будет, но если только в портативной версии, т.к. надо будет выполнить внешнюю программу (ffmpeg). А вообще в таком случае сначала надо будет сделать просто кнопку "скачать" рядом с трансляцией.

**Comment by Pmmlabs** [comment]
Готово https://github.com/Pmmlabs/OpenPeriscope/commit/4ad7064950baeec054ee8f18d7208c36e1a75287

**Comment by Vol-2016** [comment]
>Потестируй и скоро будет новый билд

Проинструктируй, как обновить портативную версию
 (в броузерном варианте эти обновления не проявляются вроде?)

**Comment by Pmmlabs** [comment]
я на главной странице описал (Using as standalone application), если будут вопросы  пиши мне в личку на 4pda

**Comment by Vol-2016** [comment]
>пиши мне в личку на 4pda
там

**Comment by Vol-2016** [comment]
1) Поскольку вполне вероятно, что LIVE-трансляция будет стерта сразу по окончании, 
то автозакачиваться должны бы одновременно и видео, и соответствующие титры (2 threads), причем хорошо бы, чтоб не только "SRT", но и "Load-history" (жаль же терять подробности).

2) И тут опять повторю: при текущем способе записи "SRT" - при длительности более 2ч 40м - стабильный ОБЛОМ (ошибка сети и никакого файла). Исправить это необходимо. Причем текущий способ записи "Load-history" работает всегда, а обрыв трансы не уничтожит записанного до обрыва. И если слегка изменить процедуру - то получать SRT можно будет и после трансы, из Load_history, ничем не жертвуя в последней.

3) Может,  снабдить членов списка Following твиттерской фичей сигналить цветом о своем "On Air", когда LIVE ? По-моему, это будет не рюшечка, а реально удобство.

**Comment by Vol-2016** [comment]
5) 
![auto_load](https://cloud.githubusercontent.com/assets/18728512/17554564/22b24cba-5f14-11e6-85b9-ee726be5d4f1.png)

**Comment by Vol-2016** [comment]
![nw_auto_load](https://cloud.githubusercontent.com/assets/18728512/17554664/9bf8b0aa-5f14-11e6-9e4d-7db31185e244.png)

**Comment by Vol-2016** [comment]
![image](https://cloud.githubusercontent.com/assets/18728512/17554697/d143cb50-5f14-11e6-843d-488f4dcc22fb.png)

**Comment by Pmmlabs** [comment]
Добавил правильное именование трансляций - дата трансляции и название, для ручной и автозакачки.
