### ISSUE TITLE
Periscope authentication

### ISSUE THREAD

**Issue by ywj7931** [Pmmlabs/OpenPeriscope#27]
Hello,

Thank you very much for your documentation, can you give an example how to log into periscope api?
https://api.periscope.tv/api/v2/loginTwitter

Do I just need to post this url, and feed the parameter with user id, access token and secret token?

**Comment by Pmmlabs** [comment]
Hello, @ywj7931 
Yes, it's right, but you can't use tokens from your developer panel, because only Periscope's tokens are accepted. Search for it in google, it's easy.
