### ISSUE TITLE
Не работает чат

### ISSUE THREAD

**Issue by aakldey** [Pmmlabs/OpenPeriscope#3]
Я так понимаю что-то поменялось в API перископа, пишу сообщение, но до трансляции оно не доходит, есть идеи?

**Comment by Pmmlabs** [comment]
Да, действительно отправка сообщений перестала работать. Periscope изменил технологию чата, теперь сообщения идут через вебсокеты а не через PubNub, надо будет переписывать код.

**Comment by Pmmlabs** [comment]
Скорее всего, отправлять сообщения получится только через версию для NW.js, т.к. похоже на то, что есть ограничение на домен - разрешено подключаться к вебсокету только с домена periscope.tv

**Comment by Pmmlabs** [comment]
@aakldey починил чат. Но работает только если запускать через NW.js, а не как userscript.
