### ISSUE TITLE
Авторизация -  Periscope consumer secret

### ISSUE THREAD

**Issue by kuaga** [Pmmlabs/OpenPeriscope#34]
1. Не до конца понятно как и почему не могу авторизоваться в Open Periscope, хотя и получил Consumer Key (YfJtfxNSTDlOl3EKSbweNUprn) из твиттера https://twitter.com/apps
2. Так же не понятно как выполнить авторизацию с помощью sms

Было бы хорошо если будет какой нибудь туториал со скринами а лучше видео как авторизоваться в приложении

**Comment by Pmmlabs** [comment]
На главной странице репозитория всё написано. Используй гугл и голову.

ключ от своего приложения не пойдет, только перископный.
