### ISSUE TITLE
Private transmission recording

### ISSUE THREAD

**Issue by kewalsk** [Pmmlabs/OpenPeriscope#35]
Is it working for live private transmission? There is no hls_url in accessChannel response.

**Comment by Pmmlabs** [comment]
Playing video in browser window doesn't work, because it's impossible to share private broadcast. But getting steam link (and downloading) works. At least, worked a week ago. If today there's no hls_url, I will fix it soon.

**Comment by kewalsk** [comment]
I know that in browser it can't work. Dowloading a replay works fine because the replay_url is taken, but for live stream there is no hls_url field in accessChanel response. I tested this since beginning of September just after you added this functionality and never got stream link. The private transmission for testing was sent from Android device, maybe it works from other kind of devices. I even tried to take the other urls that are present in accesssChannel response such as rtmp_url or lhls_url (now this field is missing) but without success.

**Comment by Pmmlabs** [comment]
Just checked it, and you are right, there's no direct link for live streams, I mixed it with replays. But there's rtmp_url instead. However, I didn't manage to play this link in player and don't know how to build working link. I will try to find out this.

**Comment by Pmmlabs** [comment]
There's `lhls_url` now, I've added it 10d532306961055779b63c86337dd8d33470256c but no luck with downloading, 403 htto error. Seems to be  some cookies is needed
