### ISSUE TITLE
При входе начинает качать всё из подписок

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#36]
кстати баг который очень не веселый это когда ты 1ий раз авторизируешься в приложении и ставишь галочку авто загрузки оно начинает выкачивает все записи которые есть в списке Following, хотя они по сути не нужны так как это прошлые)) защиту бы что ли какую-то от этого ( авто донлоад же должен качать новые записи )

**Comment by a1ex7** [comment]
Я так понимаю, что при открытой страничке он должен периодически опрашивать появились ли новые трансляции (либо как то по-другому, по аналогии с нотификациями) и если появилась - тогда писать. У меня это было сделано большим красным переключателем Start Monitoring, Stop Monitoring. Оставляешь страничку и уходишь. А оно само пишет. Типа вот такого [Скрин](http://i.imgur.com/qpyVBdi.png)

**Comment by Pmmlabs** [comment]
Да, именно так и сделано, просто нет кнопок старт и стоп, и нет определения, это первый опрос ленты или нет, т.е. как только ты поставил галку, программа думает что появились новые трансляции. Наверное, стоит вообще выпилить из автозагрузки повторы.

**Comment by Pmmlabs** [comment]
Решено отключением автозаписи повторов

**Comment by a1ex7** [comment]
Предлагаю оставить, но выбирать для каких пользователей автозагружать. Т.е. в приоритете не тип трансляции, а пользователь который транслирует.

Пример, пропустил Live трансляцию, начал писать с середины (ну или сбой какой - не записалась). После завершения начал писать Повтор. В итоге - получил полную трансляцию.

**Comment by Pmmlabs** [comment]
это уже фича риквест, в отдельный тикет надо.
> После завершения начал писать Повтор.

предлагаешь все трансляции писать по два раза? сначала лайв, а потом повтор?
