### ISSUE TITLE
Ffmpeg broken pipe error

### ISSUE THREAD

**Issue by fakirpic** [Pmmlabs/OpenPeriscope#38]
![5695253758fc417ca8b609aa6f373298](https://cloud.githubusercontent.com/assets/5578194/18842925/6b9ab518-841f-11e6-9eba-ea648244bd53.jpeg)

i always get this error while trying to broadcast a stream?

**Comment by Pmmlabs** [comment]
Streaming not working at all for now :disappointed: see #20
