### ISSUE TITLE
Экспорт в SRT

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#4]
Функция экспорта истории чата в формат субтитров SRT
спецификация: http://www.visualsubsync.org/help/srt

**Comment by Pmmlabs** [comment]
Выполнено: https://github.com/Pmmlabs/OpenPeriscope/commit/f18d7aef520d02975b3ee50c25eb3c27da4e4573
но лучше еще сделать в ASS, т.к. там гораздо больше возможностей, например выравнивание по левому краю.

**Comment by Vol-2016** [comment]
Все-таки 3-х часовая трансляция с интенсивным чатом в SRT - точно не экспортируется: 
"Ошибка сети".
Очередной пример - https://www.periscope.tv/dmitry_dibrov/1rmGPEeLVXXJN

**Comment by Vol-2016** [comment]
1) Уточнение:  "Ошибка сети" - для трансляций дольше 2 ч. 40 мин.
При этом все, что скачивалось и обрабатывалось, - теряется. 
(А не терялось бы, будь, к примеру, по методу Load history).

2) Было бы удобнее, чтобы имена файлов видео и субтитров - совпадали
(т.е. чтобы начало и там, и там было типа "[2016-06-09 00-42]").
