### ISSUE TITLE
Формат для сохранения видео

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#41]
Пожелание. Формат для сохранения видео сделать таким же как в скрипте n3tman. Т.е. создается папка с именем пользователя. А внутри по виду [2016-10-01 22-58] Кто там трансу хотел.ts Квадратные скобки это я уже сам в скрипте дописал. Мне так удобнее. А для LIVE трансляций вот так [2016-09-06 18-25] [Live] Туц, туц👀.ts

**Comment by Pmmlabs** [comment]
ZGUxODAy писал
>  не удобнее делать время файла загруженного вот так Автор - Название трансляции [2016-10-09_17.15].mp4 ? так легче сортировать

**Comment by Vol-2016** [comment]
ZGUxODAy не прав.
Название должно начинаться именно с даты+времени трансляции (заметь, эта последоватедьность знаков имеет строго постоянную длину, что удобно для Column-mode сортировки названий трансух) + имя_автора + авторское_имя_трансы. 

Лично мне еще удобна моя модификация формата имени трансляции в скрипте by n3tman (туда добавил пометки на LIVE/REPLAY со счетчиком попыток, - для REPLAY сразу после неполного LIVE,  учитывая неопределенность промежутка между окончанием LIVE и моментом возможности начать REPLAY).

**Comment by Pmmlabs** [comment]
Оставляю формат Дата_время_автор_название
