### ISSUE TITLE
автоскачивание только 3 секунды

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#45]
очень странно как то все если идет трансляция и я нажимаю скачать он скаачивает эфир нормально может пропускает пару кадров но то ерунда. но когда стоит авто загрузка при уведомлени о новой трансляции он почему то скачивает только 3-15 секунд и все на этом закрывает загрузку и больше не скачивает или битый файл вообше хотя по размеру видно что там нет даже 1МБ. не привязано ли оно как то к уведомлениями? ну мол уведомление закрылось и ffmpeg тоже с ним) мне просто не понятно почему в ручном режиме он скачивает онлайн эфир а в автопилоте всегда только 3-15 секунд

**Comment by Vol-2016** [comment]
У меня на Win7 - несколько иначе (вообще-то уже сообщал, но добавлю подробностей).
1) Автозакачка - чаще дает битые файлы (размером 500kb...3mb, но нередко и выше), но бывают и небитые видео. Возможно - тут влияют помехи в канале, противодействие которым в OpenPeriscope, видимо, не предусмотрено... (Кстати, битые от небитых легко определить по колонке "Продолжительность": если непустая, то небитый).
2) Ты пишешь, что у тебя "уведомление закрылось и ffmpeg тоже с ним", у меня - много хуже:
процессы ffmpeg не закрываются и висят до конца сеанса OpenPeriscope.
3) Иногда автоскачиваются Live-трансы не того, на кого подписан, а того, на кого он пригласил  (в OpenPeriscope не продублированы такие настройки Periscope, как запрет на "Followed User Shares Broadcast", и видимо - зря).

**Comment by Pmmlabs** [comment]
Товарищи тестировщики, обновитесь пожалуйста, и воспроизведите этот баг с включенной галочкой **Debug mode**
По неизвестной причине, после добавления логирования у меня с этой галочкой все трансляции скачиваются небитые!

**Comment by Vol-2016** [comment]
> с этой галочкой все трансляции скачиваются небитые!

 У меня - тоже! Причем нет больше и зависших процессов ffmpeg!  Сюрприз, ага :)
Раз так - не худо бы добавить память состояния чекбокса "Debug mode" для последующих сеансов OpenPeriscope...

**Comment by Pmmlabs** [comment]
Да не, там видимо дело было в том что не было потока вывода для запущенного ffmpeg, выводить текст было некуда, вот он и вешался в ожидании. Т.е. я просто добавлю вывод лога в память, в переменную например, и все будет также работать.

**Comment by Vol-2016** [comment]
> я просто добавлю вывод лога в память, в переменную например

Давай (по возможности не затягивай, оттестирую без промедления :)  )

**Comment by Vol-2016** [comment]
Однако только что получил контр-пример: 
висит процесс ffmpeg при отмеченном чекбоксе "Debug mode", 
причем это был прямой LIVE из подписки  (сейчас-то уже REPLAY, на моих глазах).
Так что "Video Repair" под рукой вполне уместен, к сожалению.

**Comment by Pmmlabs** [comment]
а на момент начала записи чекбокс был включен?

**Comment by Vol-2016** [comment]
да

**Comment by Pmmlabs** [comment]
Закоммитил фикс, сейчас должно нормально работать. Если будет зависание - открой консоль, выполни `ffLog` и пришли мне последние 10 строк

**Comment by Vol-2016** [comment]
В каком режиме тестить: с чекбоксом чекнутым или нет?
(пока смотрю при чекнутом, но вообще-то переделано, чтоб и при нечекнутом, так?)

**Comment by Pmmlabs** [comment]
да, теперь этот чекбокс не влияет на автозагрузку

**Comment by Vol-2016** [comment]
>  Если будет зависание - открой консоль, выполни ffLog и пришли мне последние 10 строк

Зависание с EXE все-таки случилось (был прямой LIVE, длит. около 4 мин,). 
Вызвать консоль путем F12 - не получается.
Может, забыл, как надо? 
Проинструктируй.

**Comment by Pmmlabs** [comment]
галочку Debug mode лучше убрать, много лишнего выпадет. выполнить ffLog надо так: в строчку внизу страницы (где синяя галочка) ввести `ffLog` и нажать Enter

**Comment by Vol-2016** [comment]
Итак: убрал галку Debug, вызвал консоль, ввел внизу страницы после синей галки ffLog, нажал Enter, -- после паузы получил вот такие последние строки лога:

![image](https://cloud.githubusercontent.com/assets/18728512/19563800/0267adf2-96ea-11e6-98f0-8f4076f97a00.png)

-- только ведь автозакачек было много, и в конце лога показан один из файлов удачных закачек, а та зависшая осталась где-то вначале лога - 

![image](https://cloud.githubusercontent.com/assets/18728512/19564006/bf5e27c4-96ea-11e6-9c5c-cd61c69ae90c.png)

-- так почему важны именно последние 10 строк, не улавливаю...

**Comment by Pmmlabs** [comment]
Потому что если случается какая-нибудь фигня, то обычно в последних 10 строчках есть сообщение о рельной ошибке. Но в приведенных тобой логах всё нормально, так что да. наверное сообщение обошибке осталось где-то раньше. А вообще странно. я же по сути сделал то же самое, что делала галочка debug mode - а результат получился другой. Или раньше с галочкой тоже не всегда нормально скачивалось?

**Comment by Vol-2016** [comment]
> Или раньше с галочкой тоже не всегда нормально скачивалось?

Именно (хотя и не слишком часто).
***
А можно сейчас сохранять полный лог консоли (я вот не нашел нормального способа) ?
Если нет - то надо бы, сам видишь...
И вообще: EXE, повторю, нуждается в таком же контекстном меню, какое есть в скрипте/браузере (также и для сохранения Load history, и копирования ссылок из чата и др. мест в EXE...)
