### ISSUE TITLE
can't get periscope oauth

### ISSUE THREAD

**Issue by Git-David-Dai** [Pmmlabs/OpenPeriscope#49]
I have already get twitter's oauth by using it's sdk,and then when I POST to "https://api.periscope.tv/api/v2/loginTwitter" API with the http body 
` @"session_key"    : session.authToken,@"session_secret" : session.authTokenSecret,@"user_id"             : session.userID,  @"user_name"      : session.userName,`
(on IOS,some key optional) .end then receive the 401 error code.

here is my question : It's useful for this api now?

**Comment by Pmmlabs** [comment]
You can't use tokens from your developer panel, because only Periscope's tokens are accepted.
