### ISSUE TITLE
Уведомления о новых трансляциях

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#5]
Показывать уведомления, когда кто-то из подписок начинает трансляцию.
Push API работает не во всех браузерах, точнее только в самых-самых новых версиях, поэтому надо что-то другое. Хотя ajax по таймеру как-то не хочется.

**Comment by a1ex7** [comment]
Пусть может не постоянный мониторинг, а хотя бы при любом обновлении страницы уведомление о новых трансах где-нибудь на видном месте в углу, чтобы не переходить постоянно на Folowing и не жать Refresh

**Comment by Vol-2016** [comment]
У меня на одной из вкладок в Хром трансляции интересующих юзеров отслеживает целая батарея кнопок,
каждая либо синяя, либо красная, в зависимости от того, идет ли соответствующая трансляция.

Там сначала код датчика (одного на всех) --

<script>
window.twttr=function(t,e,r){var n,i=t.getElementsByTagName(e)[0],w=window.twttr||{};
return t.getElementById(r)?w:(n=t.createElement(e),n.id=r,n.src="https://platform.twitter.com/widgets.js",i.parentNode.insertBefore(n,i),w._e=[],w.ready=function(t){w._e.push(t)},w)}(document,"script","twitter-wjs")
</script>

-- а потом отслеживаемые юзеры --

<a href="https://www.periscope.tv/user1" class="periscope-on-air" data-size="small">user1</a>
<a href="https://www.periscope.tv/user2" class="periscope-on-air" data-size="small">user2</a>
<a href="https://www.periscope.tv/user3" class="periscope-on-air" data-size="small">user3</a>

Но вместо цвета - можно же и звук (отмечая в таком случае только начало трансы) ?

**Comment by Pmmlabs** [comment]
Это подключение твиттеровой библиотеки виджетов. Я посмотрел на сетевые запросы, думал сначала, что там у них long_poll, (ну это когда сервер специально очень долго отвечает на запрос, чтобы клиент слал запросы без задержки, подряд, а ответ возвращается только когда происходит событие) но оказалось что у них там обычный ajax с задержкой 15 секунд. Хотя, запрос отрабатывает быстрее чем API перископа. Поэтому лучше делать через эту штуку. Спасибо за совет.

**Comment by Vol-2016** [comment]
Удалил, потому как вдруг показалось, что не пойдет... Если ошибся и таки пригодится - хорошо, что гитхаб дублирует на почту :)

Но я с инфой: посмотри страничку https://www.periscope.tv/joe .
Дело не столько в самой трансляции, хотя и она интересна ("Working. JavaScriptAScope"):
взгляни, сколько времени она сохраняется без всякого #save - 14 дней !
Сдается, этот Джо плотно связан с Periscope, если не инсайдер, так хакер в теме, и с ним пообщаться - так может и фич OpenPeriscope добавится :)

**Comment by Pmmlabs** [comment]
У него id 97, по-любому близок к разработчикам. И я думаю, он в принципе не одобрит существование неофициального клиента )

**Comment by Pmmlabs** [comment]
Ну короче посмотрел я его трансляцию, он там пишет сайт перископа, т.е. плеер трансляций. Ничего нового и секретного там нет, исходники фронт-енда всегда в открытом доступе. Я уже изучал их, единственное, что они почему-то написаны как будто на Node.js и потом запакованы в один файл для использования в браузере. Распакованные исходники я залил в свой репозиторий https://github.com/Pmmlabs/periscopetv , пока не удалось их запустить, но я это и не преследую, потому что главная их ценность - для исследовательских целей.

**Comment by Vol-2016** [comment]
Интересно, спасибо.

(на его id не догадаться взглянуть - это я отличился :)

**Comment by Pmmlabs** [comment]
Готово! https://github.com/Pmmlabs/OpenPeriscope/commit/2e8f9c64f97b889f33b75e2b80cd4784043534e7
включается через настройки 
![untitled](https://cloud.githubusercontent.com/assets/2682026/15362089/acb2971a-1d1c-11e6-9053-e7ebc52757ca.png)

**Comment by Vol-2016** [comment]
Ага, заработало. 
Тестирую... 
Что заметил:
- в текст уведомления - еще бы и время начала/конца трансляции (в оф. - есть)...
- в уведомлении есть линк на исключение из уведомлений - еще бы и флаг для каждого в списке Following (в оф. - есть)...

**Comment by Vol-2016** [comment]
Кстати,
клики по уведомлениям плодят вкладки с трансляциями, голосящими одновременно, - 
так что очень на руку экспериментальная фича Хрома: 
chrome://flags/#enable-tab-audio-muting .

**Comment by Pmmlabs** [comment]
а в firefox она давно уже не экспериментальная и работает :)

**Comment by Vol-2016** [comment]
ага, только со скриптом (у меня) лис подглючивает, а хром (тьфу-тьфу) нет.

**Comment by Pmmlabs** [comment]
Я пользуюсь лисом, вроде ничего не замечал. Что конкретно подглючивает?

**Comment by Vol-2016** [comment]
с лисом не часто, в подробностях не  припомню... в общем, погоняю и доложу.

**Comment by Pmmlabs** [comment]
> в уведомлении есть линк на исключение из уведомлений - еще бы и флаг для каждого в списке Following (в оф. - есть)...

А это разве относится не к push-уведомлениям? у нас то не пуш, а просто обновление ленты подписок.

**Comment by Pmmlabs** [comment]
Добавлено отображение времени https://github.com/Pmmlabs/OpenPeriscope/commit/bd7f5ce6dfcadae1c423cd81098c40bc0bcba098
Ссылки в уведомлениях показывать невозможно, только текст. Соответственно, замьютить из уведомления - невозможно. (Только если писать свой движок уведомлений внутри страницы, но это пока нафиг)
