### ISSUE TITLE
Странный "Downloads path" для скрипта

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#52]
Попытка установить для скрипта тот же путь, что и для EXE -

![dwnld_path_4_exe](https://cloud.githubusercontent.com/assets/18728512/19421994/d57d6fa6-9415-11e6-9665-ceeaa1808baf.png)

-- приводит к странному результату:

![dwnld_path_4_script](https://cloud.githubusercontent.com/assets/18728512/19422003/00a20390-9416-11e6-8805-375e521bbba3.png)

Что за "fakepath" ??
И почему вместо пути -  файл (mp4) выскочил ??

**Comment by Pmmlabs** [comment]
Этой настройки в скрипте вообще не должно быть. Уберу.
