### ISSUE TITLE
Do not logout

### ISSUE THREAD

**Issue by chrisbog94** [Pmmlabs/OpenPeriscope#56]
Using the consumer secret that I have, I now get:
oauth error 401: Request token failed

Do not logout or you may also get the same error.

**Comment by Pmmlabs** [comment]
Cause of this is a ban of all protocols other than `twittersdk://` in `oauth_callback` parameter

**Comment by Pmmlabs** [comment]
Fixed for standalone version 6737fd814cd635471c88c80917f730e825750bce

**Comment by Pmmlabs** [comment]
Fixed for userscript version
