### ISSUE TITLE
"Downloads path" в ветке "nwjs13"

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#57]
При попытке задать путь - в данном случае "D:\\_PERISCOPE\Videos_OP" -
вместо этого получаем список всех файлов в этой папке:

![nwjs13_branch](https://cloud.githubusercontent.com/assets/18728512/20036722/3f37a234-a421-11e6-925b-50409a5e3e8b.png)

**Comment by Vol-2016** [comment]
все-таки - поправить бы,  чтоб как в основной (nwjs0123) ...

**Comment by Pmmlabs** [comment]
Я то конечно исправил, но для пустых папок работать не будет - это баг хромиума https://bugs.chromium.org/p/chromium/issues/detail?id=360412

**Comment by Vol-2016** [comment]
К сожалению - не помогло. 
"Downloads path" показывает ВСЕ файлы, какие когда-либо там были (но сейчас-то их там нет), 
а способа отредактировать соответствующий 288 Кбайтный файл -
chrome-extension_bjhbjocpihnfbncblmbgdpacnmbkmadm_0.localstorage - не вижу.
Попытки же убрать старую Userdata и зарегистрироваться по-новой - не проходят: 
и секретный ключ принимается, и Твиттер забирает логин и пароль, но затем - якобы нет  связи с неким сервером, "страница возможно удалена" (что-то типа того). Вот так вот.

**Comment by Pmmlabs** [comment]
может ты опять не обновил или ветку не переключил?
Только что проверил на nwjs-v0.14.2 работает

**Comment by Vol-2016** [comment]
Наоборот, у меня эта ветка в перманентном обновлении,  как по OpenPeriscope, так и по Node/nwjs -

> Только что проверил на nwjs-v0.14.2 работает
 
- у меня сейчас последние: Node-7.4 и nwjs-0.19.5 (для того ветку nwjs13 и держу).

Но из-за твоего "nwjs-v0.14.2" вдруг вспомнилось: 
то, что пропала возможность регистрироваться - заметил на версиях именно после 014x.

**Comment by Vol-2016** [comment]
Так, попробовал загрузить вручную с выбором .ts - получил вот что:
"[NULL @ 00a0b600] Requested output format 'mpegts' is not a suitable output format
D:\_PERISCOPE\Videos_OP\2017-01-11_08.45_zari_nz_новая зеландия. вулкан закончился. теперь можно и поговорить=).ts: Invalid argument"

**Comment by Pmmlabs** [comment]
пропала возможность регистрироваться???

**Comment by Vol-2016** [comment]
именно
