### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by maed911** [Pmmlabs/OpenPeriscope#59]
Hi,
Since this afternoon, it is not possible to me to synchronize, only the menus appear.
Is this normal?

ex:
![capture d ecran_2016-11-12_19-23-36](https://cloud.githubusercontent.com/assets/23422025/20239992/d19a8632-a90d-11e6-9bb2-bfd4082dfe2c.png)

Thanks

**Comment by Pmmlabs** [comment]
Hi, @maed911 
It's possible if your account has been banned by Periscope.
Anyway, show me the logs (click to button with 3 lines in top right corner), and I will make more clear message box for this case.

**Comment by maed911** [comment]
thanks for the reply.
My account is disable.
![logs](https://cloud.githubusercontent.com/assets/23422025/20242484/cb81e9da-a92f-11e6-9012-b1be0d92ba90.png)
