### ISSUE TITLE
уведомления

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#61]
у вас работают уведомления в 12 версии nwjs ? вроде проверил на разных сборках linux такая же ерунда не включаеться галочка "Enable notifications" вернее она включаеться но эффекта ноль а если перезапустить браузер галочка уже будет снята

**Comment by Vol-2016** [comment]
(Win7)
в EXE - работают, в скрипте - нет (в EXE ветки nwjs13 - тоже нет).
