### ISSUE TITLE
Update.bat for OpenPeriscope.exe

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#62]
:: (7-Zip v.16.04 , Win7-x86)

@echo off

7z x OpenPeriscope-master.zip
::del OpenPeriscope-master.zip

7z x -t# OpenPeriscope.exe

::del OpenPeriscope.exe
rename OpenPeriscope.exe -OpenPeriscope.exe

7z a 2.zip .\OpenPeriscope-master\\*

copy /b 1.exe+2.zip OpenPeriscope.exe

rd /q /s OpenPeriscope-master
del 1.exe
del 2.zip

:pause
exit

**Comment by Pmmlabs** [comment]
Перенес в раздел wiki https://github.com/Pmmlabs/OpenPeriscope/wiki

**Comment by Vol-2016** [comment]
Оказалось, можно и короче! -

@echo off
7z x OpenPeriscope-master.zip
::del OpenPeriscope-master.zip
7z a -tzip:s80m OpenPeriscope.exe .\OpenPeriscope-master\*
rd /q /s OpenPeriscope-master
:pause 
exit
