### ISSUE TITLE
Не хватает фичи промотки вперед при записи "Load history" (в REPLAY)

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#64]
Нередки случаи преждевременного обрыва закачки "Load history" (в REPLAY).
Причем попытки перезакачать приводят к остановке на том же самом месте. 
А возможности попытаться перескочить через такое гиблое место и качать дальше - сейчас нет.
(К примеру,  **youtube-dl**  имеет ключик **--skip-unavailable-fragments**)
***
Сдается, новые REPLAY требуют изменений и в форматах Load_history/RST: 
есть намертво обрывающиеся уже в самом начале...

**Comment by Pmmlabs** [comment]
да, тут скорее не промотку надо делать, а чтобы не обрывалось. Скорее всего формат чата изменился.

**Comment by Vol-2016** [comment]
Ага, с LIVE у Load_history (как было и у видео) - OK, что как бы намекает.

**Comment by Pmmlabs** [comment]
Проблема исправлена, фичу делать не буду.
