### ISSUE TITLE
recover partial files

### ISSUE THREAD

**Issue by diga76** [Pmmlabs/OpenPeriscope#68]
Hi, 
compliments for your great program.
I have just a question: after I close the application, when there are some recording streaming, I find the mp4 files but I cannot view them.
Is there a way to recover and view these partial files ?
Thank you very much

**Comment by Pmmlabs** [comment]
Hi, thanks for the report.
Bug fixed.
You can use [Untrunk](https://github.com/ponchio/untrunc) to recover mp4 files.

**Comment by diga76** [comment]
Thank you very much for your fix, very quick.
I am trying with Untrunc but I am a Windows user and I have many problems compiling Untrunc on my OS.
Do you know if exist a Windows version or similar programs?
Thanks a lot

**Comment by Vol-2016** [comment]
diga76
try  http://www.grauonline.de

**Comment by kewalsk** [comment]
I suggest you to change ffmpeg call to not convert stream into mp4 and leave it unconverted as ts file. (Then you can convert it to mp4 later if you really want to have mp4 for any reason but it's not necessary)

Just remove line from Periscope_Web_Client.user.js:
`'-bsf:a', 'aac_adtstoasc',`
and change 
`settings.downloadPath + folder_separator + name + '.mp4'`
into
`settings.downloadPath + folder_separator + name + '.ts'`

I'm doing downloads this way and never had problem with broken/stopped/corrupted files.

**Comment by diga76** [comment]
Thank you for your suggestions.
To recover broken videos I tried with an Ubuntu live usb and Untrunc and It seems working fine.
I will try the last OpenPeriscope version that should correct the exit problem, if I have other problem with broken video I will change the output format with ts.
Thank you very much.

**Comment by Pmmlabs** [comment]
@kewalsk , thanks, I will add output format setting.
@diga76 I haven't built latest version as .exe yet, therefore you can run it only using NW.js (instructions on the main page) , for a while

**Comment by diga76** [comment]
To update my exe I used the script in this [page](https://github.com/Pmmlabs/OpenPeriscope/wiki#how-to-update-portable-version-exe). Is correct or I need the new exe ?
In previous post I see the possibility of new setting for output format, do you think it would be usefull a setting to choose if in the file name put the account name (as now) or the user account ?
Thanks

**Comment by Pmmlabs** [comment]
yes, you can update this way.
>  do you think it would be usefull a setting to choose 

I don't. But you can create new issue about it, and may be somebody will agree.

**Comment by diga76** [comment]
Ok, perfect. I suppose the user account is useful to recover the page of suggested, by followed, streams or to recover the user from file, but no problem is only an idea.
Thank you very much for your work.
