### ISSUE TITLE
Download status

### ISSUE THREAD

**Issue by openlover88** [Pmmlabs/OpenPeriscope#71]
Hi,

its possible to add more info of current downloads? Like date, detailed status of every download (perfect to see if the download is stopped).

Will be great too if every download can be stored in separated folders for every user 

Thanks and good job!!

**Comment by Pmmlabs** [comment]
Hi. I  am [already planning](https://github.com/Pmmlabs/OpenPeriscope/issues/48) to implement "download manager" like in browsers, so it can be in future releases.
