### ISSUE TITLE
Насколько верно показываемое время трансляции -

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#72]
-- начало, конец, длительность, временнАя зона?
У меня есть сомнения на этот счет.  На прилагаемой фотке зафиксированы несколько временнЫх параметров одной и той же трансляции, но из 3-х источников: 
страница https://www.periscope.tv/Amigood/1BdxYgOjRLYGX , скрипт by n3tman и OpenPeriscope.
Если вглядеться в фотку - есть несоответствия:

https://drive.google.com/open?id=0B7M0DPHIQGRQY0VpV2FpMS13dlE

**Comment by Pmmlabs** [comment]
У трансляций существует несколько полей, содержащих время: created_at, start, updated_at, ping - возможно разные программы используют разные поля. Плюс скрипт n3tman не конвертирует время в соответствии с часовым поясом - отсюда разница в 3 часа

**Comment by Vol-2016** [comment]
Из фотки видно, что время по скрипту n3tman и время по сайту перископа - совпадает, но меня в данном случае интересуют огрехи не n3tman, а OpenPeriscope: что за время именно он показывает?
Из фотки можно выжать, например, несоответствие "заявленному" времени - светлое время дня в NYC, но чтоб еще нагляднее: 
смотрю LIVE из NYC. и показываемое OpenPeriscope-ом время трансляции - мое (по Москве), а не местное или глобальное ...

**Comment by Pmmlabs** [comment]
А я бы сказал, что моё время (22:39 мск) как раз ближе к времени n3tman (19:40 UTC) чем на сайте (20:06 UTC)
И да, в OpenPeriscope показывается время в часовом поясе пользователя, я считаю это удобно.

**Comment by Pmmlabs** [comment]
Скорее всего, на сайте показывается `updated_at` т.е. фактически время окончания.
А в скрипте - не дата создания трансляции, а дата когда человек нажал кнопку "start broadcast" (или как она там в телефоне называется), возможно это даже более корректно.

**Comment by Vol-2016** [comment]
В данном случае время по сайту и по скрипту совпадает: 
начало по скрипту (19:40:04) + длительность по сайту (26:23) = конец по сайту (20:06:05).
У  OpenPeriscope с длительностью (00:26:55) - OK, но вот 22:39 - 19:40 = 3 часа, тогда как разница между Мск и NYC - 8 часов ...

Что касается удобства показа времени в часовом поясе пользователя - то вдобавок указание разницы во времени с источником трансы не менее удобно :)

**Comment by Pmmlabs** [comment]
Придется провести небольшой ликбез. Есть время по Гринвичу, оно же UTC, часовой пояс +0. Восточнее от Гринвича время увеличивается, западнее - уменьшается. Так, в Москве часовой пояс +3 означает, что когда в Гринвиче 19:40, в Москве 22:30. Нью-Йорк находится западнее Гринвича, поэтому часовой пояс там с отрицательным знаком, а именно -5. Это значит, что когда в Гринвиче 19:40, в Нью-Йорке 14:40. Таким образом, когда в Нью-Йорке 14:40, в Москве (+3 - (-5))=+3+5=+8 часов=22:40

**Comment by Vol-2016** [comment]
Насчет ликбеза: 
так где в OpenPeriscope пометка о часовом поясе? 
Это что - предлагается погуглить по названию (Нью-Йорк) ?
"Я считаю это удобно" - ты уверен ? :)

**Comment by Pmmlabs** [comment]
Пометки о часовом поясе ведущего быть не может, т.к. API не возвращает такой информации, а только время в GMT. В принципе можно угадывать пояс по геотегу, но они опять же проставляются не всегда, да и то бывает что проставляются неправильно.
