### ISSUE TITLE
Подпапки и наименование файлов записанных/скаченных трансляций

### ISSUE THREAD

**Issue by Copelaw** [Pmmlabs/OpenPeriscope#74]
Возможно ли внести изменения, чтобы создавалась подпапка, которая бы имела такое же наименование как и аккаунта перископа? А уже в данную подпапку помещались файлы трансляций с соответствующим наименованием? Например: если аккаунт имеет имя 09876, имя пользователя asdf, а название трансляции 12345, то папка будет иметь имя 09876, а файл трансляции внутри данной папки имя "09876 (asdf) [YYYY-MM-DD hh-mm-ss] 12345.mp4". (В квадратных скобках формат даты)

**Comment by Pmmlabs** [comment]
Такое пожелание уже было в https://github.com/Pmmlabs/OpenPeriscope/issues/41 , возможно сделаю

**Comment by Pmmlabs** [comment]
Реализовано: #89
