### ISSUE TITLE
Чат не работает в некоторых трансляциях

### ISSUE THREAD

**Issue by sinbadxiii** [Pmmlabs/OpenPeriscope#76]
Сообщения не отсылаются в некоторых трансляциях.

Есть ли вероятность того что при отправке сообщения и формирования timestamp и ntp учитываются часовой пояс трансляции?

**Comment by Pmmlabs** [comment]
Нет, эти форматы не включают в себя часовой пояс, поэтому всегда содержат время по Гринвичу

**Comment by sinbad13** [comment]
Заметил такую особенность, если под одной и той же учеткой логиниться в periscope.tv и OpenPeriscope тогда сообщение в OpenPeriscope отсылается  нормально, но как только закрывают сайт periscope.tv, то сообщение уже не отсылается

**Comment by lxprost** [comment]
@sinbadxiii, выставили таймауты на время между сообщеними. Так же повторные сообщения не проходят. Раньше менее жестко фильтрация стояла, теперь вот так вот. Или они у вас совсем не отправляются?

**Comment by sinbadxiii** [comment]
@lxprost совсем. Например, открываю сайт http://liveomg.com/?filter=periscope.tv и в трансляциях на первой странице не отправляется ни в какую, тем более в первую десятку точно, а вот со второй страницы http://liveomg.com/index.php?filter=periscope.tv&next=101 уже сообщения начинают нормально отправляться.

**Comment by Pmmlabs** [comment]
А есть ли смысл в функционале отправки сообщений в чат, когда на официальном сайте перископа реализована эта возможность?

**Comment by lxprost** [comment]
@Pmmlabs А ты не смотрел, на сайте чат отправляется тем же методом - через тот же гейт, или там по иному сделали? Нам просто впадлу смотреть)) Если там гейт другой, лучше бы юзали его.

**Comment by Pmmlabs** [comment]
@sinbadxiii какую версию приложения ты используешь? юзерскрипт / портативную? релизную или самую свежую из репозитория?

**Comment by sinbadxiii** [comment]
@Pmmlabs использовал релиз OpenPeriscope-1.6-linux-x64.zip

**Comment by Pmmlabs** [comment]
тогда понятно. Слишком много людей было в чате, вот и не отправлялось. Просто там был баг с отображением сообщения об этом. В новой версии 1.7 это исправлено.
