### ISSUE TITLE
Consuming Periscope API

### ISSUE THREAD

**Issue by RamzyChatti90** [Pmmlabs/OpenPeriscope#77]
As a current student in Software Engineering. In this time I am preparing my final graduation project and I am working on android application that allows to stream video Live through The Persicope APi.
I am contacting you to request your help. In fact, I would like to ask you if there is any way to do this and if the Api is available to be consumed.
In anticipation of your replay, I thank you in advance for the consideration you will give to my request.

**Comment by Pmmlabs** [comment]
Hello.
Yes, you can use Periscope API, but I don't know about legal availability.
But API is not enough for streaming, because Periscope uses its own video protocol. So you will be able to send information about new stream, but not a video.
