### ISSUE TITLE
Авторизация через номер телефона

### ISSUE THREAD

**Issue by Pmmlabs** [Pmmlabs/OpenPeriscope#8]
Многие просят авторизацию через телефон, наверное чтобы зайти в уже существующий аккаунт. В документации API соответствующего метода пока нет, надо будет отреверсить.

**Comment by Pmmlabs** [comment]
Готово https://github.com/Pmmlabs/OpenPeriscope/commit/5122e90690784cf78a7123fc00a9542739d27758

**Comment by Vol-2016** [comment]
SMS не тестил, но теперь - после SIGN OUT в профиле - опять не получается ввести коды:

![key_input](https://cloud.githubusercontent.com/assets/18728512/15193201/573a6f8a-17c5-11e6-95e3-bea1945cc0a5.png)

**Comment by Pmmlabs** [comment]
Потому что ключ не тот. Надо другой, длинный.

**Comment by Vol-2016** [comment]
Да нет, хоть так, хоть этак - не хочет, зараза

**Comment by Pmmlabs** [comment]
В консоли есть какие нибудь ошибки?

**Comment by Vol-2016** [comment]
Автоматом ничего не выскакивало, а теперь в тот акк не войти и не потестить...
Но может не уловил про консоль, поясни, что надо отследить.

**Comment by Pmmlabs** [comment]
Если ты в Хроме, то надо нажать F12 и открыть вкладку Console. Ты выходишь из аккаунта, нажимаешь Sign in with twitter, и смотришь в консоль - возможно, там какие-то ошибки.

**Comment by Vol-2016** [comment]
Понятно, сделаю. 
Но с другой стороны - расскажи, куда конкретно записывалось то, что сейчас мешает и что вычистить (в реестре? в AppData?).
Конечно, под рукой ProcMon, но лучше бы напрямки :)

**Comment by Pmmlabs** [comment]
Я не знаю, что мешает.
Но если хочешь "вычистить", то вычищай локальное хранилище домена example.net, это делается по F12, вкладка Resources - Local Storage

**Comment by Vol-2016** [comment]
Вот, одинаково и для длинного, и для короткого кода:

![long_or_short_code](https://cloud.githubusercontent.com/assets/18728512/15210608/e47a1a60-183f-11e6-927c-89630940cef7.png)

И спасибо за наводку на example.net - прозевал.

**Comment by Pmmlabs** [comment]
Оказалось, Google Code больше не хостит файлы, и ссылки на crypto-js умерли. Поменял ссылки, теперь должно работать. Только я не увеличивал пока номер версии, поэтому обычным обновлением не обойтись - надо сначала удалить старый скрипт, а потом поставить заново.

**Comment by Vol-2016** [comment]
> Поменял ссылки, теперь должно работать.

Да, после этого получилось ввести код и войти через твиттер.
Но - дойти только до страницы "Example Domain" и на ней застрять.

Да, старый скрипт удалил, поставил заново...

Приаттачиваю спаренный отчет: 
вверху - от успешного аккаунта, внизу - от проблемного аккаунта, - 
после "Run_OP"  - т.е. на https://raw.githubusercontent.com/Pmmlabs/OpenPeriscope/master/Periscope_Web_Client.user.js .

(У меня Win7 + UAC + режим обычного пользователя, отсюда два акка сразу: 
верхний - с правами админа, нижний - без).

[Chrome v. 50.0.2661.94 m]

![run_script](https://cloud.githubusercontent.com/assets/18728512/15227329/4d33b094-188f-11e6-87bb-f819d998f07e.png)

**Comment by Pmmlabs** [comment]
Что такое Run_OP и Reset_OP?

**Comment by Vol-2016** [comment]
OP = OpenPeriscope (script),  
Reset_OP и Run_OP - ссылки из твоей статьи "Клиент Periscope для компьютера":

> 2. Кликните на ссылку и потом "Установить"

Второй аккаунт - @peris_cop_ -
его аватарку см. на periscope.tv/peris_cop_ -
но  при этом - как видишь ...

**Comment by Pmmlabs** [comment]
>  Reset_OP - ссылка из твоей статьи "Клиент Periscope для компьютера":

Тогда уж не Reset, а Update )

Ошибка авторизации исправлена.

**Comment by Vol-2016** [comment]
Супер !
