### ISSUE TITLE
Вопрос автору,код проги 1.7 не проходит, для авторизации твиттера.

### ISSUE THREAD

**Issue by Andrianen** [Pmmlabs/OpenPeriscope#80]
Вопрос автору, ввожу код в прогу 1.7 для авторизации твиттера, выдаёт что код не правильный, проверял несколько раз по буквам и цыфрам, всё равно код не проходит.

**Comment by Pmmlabs** [comment]
Привет. Код для всех версий одинаковый, потому что это код не для моей программы, а для API авторизации твиттера. Я только что проверил, авторизуется нормально. Если что, в правильном коде 50 символов, проверь. Если опять не подойдет, напиши мне на почту, помогу.
