### ISSUE TITLE
Что-то изменилось в режиме захода в трансляцию?

### ISSUE THREAD

**Issue by lxprost** [Pmmlabs/OpenPeriscope#81]
Соль в чем, используем бота для фильтрации чата.

Стандартный вход:

/accessChannel
и конект по ключам на точку чата
Все работает корректно. Бот коннектится, чат грабит. Напрягает другое - 
Бот отображается в списке первое время, а потом выпадает. При этом чат грабит исправно на протяжении всей трансляции

postdata на pingWatching отправляется каждые 30 секунд (меняли на 15) - толку нет.
докрутили даже боту возможность ставить сердечко каждые 15 секунд в качестве ping
-> Если бот добавлен у ведущего, но будто бы сердечко не отправляется.

Копнули дальше:
Чтобы понять в чём беда, т.к нужно реально видеть отпал бот или не отпал пустили сразу 20 штук. И тут началось самое интересное:

Входя в трансляцию пустую закрытую отображается 20 человек (что логично). Цифра не падает, все работает тип-топ. НО! Когда ты находишься на странице приложения в транляции как-бэ ноль человек.
Т.е получается так:
Счетчик чата 20, а счетчик трансляции 0

**Comment by lxprost** [comment]
Нашел новый раздел который получаем при accessChannel:

` [cookies] => Array
        (
            [0] => Array
                (
                    [Name] => Token
                    [Value] => eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbImhscyJdLCJCcm9hZGNhc3RJZCI6IjFsRHhMUk16VmR6R20iLCJHcmFudFR5cGUiOiJyZWFkIiwiR3JhbnRlZEF0IjoxNDkwNDQ3NTU2LCJHcmFudGVkVG8iOiJrYWtvcm9sZXZhMzk3NzMiLCJTdHJlYW1OYW1lIjoiMnh4UTVKQ3F6ZERaRlV1YWM4QU1DeGxGcE1sV3IyNk83Zk1lZWFYRVh4X3VLV3hLRWladXZZMnpnUVBod05mUWN3bzRwbW9UWlRnT2hfeTJyUnRxcmciLCJleHAiOjE0OTMxMjU5NTZ9.c6d-3aY5xUZZ8Ktch10V2BlDkEK4Oxxpv9_2cJP3AqM
                    [Path] => /2xxQ5JCqzdDZFUuac8AMCxlFpMlWr26O7fMeeaXEXx_uKWxKEiZuvY2zgQPhwNfQcwo4pmoTZTgOh_y2rRtqrg
                    [Domain] => .periscope.tv
                    [Expires] => 2017-03-26T13:20:13.064741676Z
                    [RawExpires] => 
                    [MaxAge] => 0
                    [Secure] => 
                    [HttpOnly] => 
                    [Raw] => 
                    [Unparsed] => 
                )

            [1] => Array
                (
                    [Name] => Service
                    [Value] => proxsee
                    [Path] => /2xxQ5JCqzdDZFUuac8AMCxlFpMlWr26O7fMeeaXEXx_uKWxKEiZuvY2zgQPhwNfQcwo4pmoTZTgOh_y2rRtqrg
                    [Domain] => .periscope.tv
                    [Expires] => 2017-03-26T13:20:13.064741676Z
                    [RawExpires] => 
                    [MaxAge] => 0
                    [Secure] => 
                    [HttpOnly] => 
                    [Raw] => 
                    [Unparsed] => 
                )

            [2] => Array
                (
                    [Name] => Digest
                    [Value] => W_1CubxQsBksuiTuwHeRxNKZVWIUvBzm0acGAw7XPiQ
                    [Path] => /2xxQ5JCqzdDZFUuac8AMCxlFpMlWr26O7fMeeaXEXx_uKWxKEiZuvY2zgQPhwNfQcwo4pmoTZTgOh_y2rRtqrg
                    [Domain] => .periscope.tv
                    [Expires] => 2017-03-26T13:20:13.064741676Z
                    [RawExpires] => 
                    [MaxAge] => 0
                    [Secure] => 
                    [HttpOnly] => 
                    [Raw] => 
                    [Unparsed] => 
                )

        )
`

**Comment by lxprost** [comment]
В целом разобрались ребята
**Шаги для входа успешного можно в документации поменять**

/accessChannel
/accessVideo -> Получить life_cycle_token (он похож началом, но в конце все таки отличается от [session] полученный в accessChannel
/startWatching -> Увеличить счетчик трансляции

**Comment by Pmmlabs** [comment]
Спасибо за сообщение, но в документации уже было описано про токен и [accessVideo](http://static.pmmlabs.ru/OpenPeriscope/#/accessVideo)
Flowchart в начале некорректный, да, но я вообще его не обновлял, со времен pubnub-a. возможно когда-нибудь и обновлю.
