### ISSUE TITLE
A lot of recordings

### ISSUE THREAD

**Issue by diga76** [Pmmlabs/OpenPeriscope#84]
Hi,
from some weeks I have a strange problem. I find a lot of recordings in my download folder. The recordings are not of followers or followings but from other accounts. Looking in Following tab I also see that these streaming are shared by account that aren't followers or followings.
I am using OpenPeriscope in an old PC and the internet connections is not very good so, with a lot of concurrent recordings, I have often some problem in the application and then some corrupted recordings.
Why OpenPeriscope records these streaming? Is there a way to stop or to inhibit these recordings?

Thanks a lot

**Comment by Pmmlabs** [comment]
Yes, this feature is planned: #55

**Comment by diga76** [comment]
Ok, perfect. I suggest, if possible, to separate streamings suggested by followers/followings (more interesting) and streamings suggested by unknown accounts (maybe less interesting).
Thank you very much and compliments for this great software.
