### ISSUE TITLE
v.1.3 - глюки

### ISSUE THREAD

**Issue by Vol-2016** [Pmmlabs/OpenPeriscope#9]
1) Не посылаются комменты (в EXE v.1.2 работало), с лайками то же...

2) SRT:  в EXE - только видимое движение в прогрессбаре, файлы *.srt не создаются...
      в Хроме - файлы *.srt создаются, но  иногда тут же исчезают...

**Comment by Pmmlabs** [comment]
1) действительно не посылаются, исправлю

2) пока прогрессбар виден, надо ждать. видимо много комментов. попробуй на какой-нибудь маленькой трансляции, например из раздела Newest
> файлы *.srt создаются, но иногда тут же исчезают...

не понял, как это. сами удаляются что ли?

**Comment by Vol-2016** [comment]
Ну да - как бы сами: успеваю заметить в папке загрузки, но вытащить оттуда - не успеваю :)
Как если бы было задано ограничение на размер файла. (Это для Хрома).

Для EXE проверил на крошечном чате из Newest - да, такие сохраняет. Но если побольше - то нет...

(Кстати, что-то у меня на VLC не получается подключить .srt ни к .m3u8, ни к суммарному .ts ...)

**Comment by Pmmlabs** [comment]
Только что проверил на Chrome 49, скачивается файл 278 кб, с последней трансляции Олега Газманова. Проверяй свой антивирус/плагины мож какие, не знаю.
VLC не пользуюсь, качаю видео в mp4 через ffmpeg (на главной странице репозитория есть инструкция), субтитры подключаются ровно. Смотрю через PotPlayer на Windows и UMplayer на Linux. Еще один пользователь писал, что на телевизоре даже подключаются эти субтитры. Может, к m3u8 и ts в принципе нельзя прицепить srt?

**Comment by Vol-2016** [comment]
Насчет Хрома - ты совершенно прав, это я лопухнулся (плагин DM с включенным перехватом закачки).
Что до EXE - то убедился, что там просто на редкость тормозная закачка. Вот попробуй скачать того же Газманова...

**Comment by Pmmlabs** [comment]
Комменты исправлены. В разделе релизов заменил файлы, перекачай.
Насчет SRT - да, немного дольше качается в портативной версии, но это уже вопрос производительности, я пока сделал просто чтобы работало, надеюсь заинтересованные люди помогут с производительностью.

**Comment by Vol-2016** [comment]
3) В отличие от скрипта - EXE не обеспечивает ни live, ни replay трансляции с periscope.tv .

И одно предложение по интерфейсу: на шаг сократить путь к кнопке "SRT",  перенеся ее со страницы чата на предыдущую, под кнопку "Chat",  напротив "Get stream link"-->"Download replay M3U".

**Comment by Pmmlabs** [comment]
В новой версии используется флеш плеер PepperFlash, потому что обычный некорректно показывает видео в горизонтальной ориентации. Перейди на https://get.adobe.com/ru/flashplayer/otherversions/ там выбери свою ОС и тип плагина PPAPI, и установи

**Comment by Vol-2016** [comment]
Странно, у меня PepperFlash и стоял, и когда вчера тестил EXE - видел, что доложил выше, а сейчас, после твоего поста, посмотрел - теперь работает., чудеса...  Ну тады OK :)

**Comment by Vol-2016** [comment]
Привет! 
Вот если приходят на ум вроде стоящие фичи - где их предлагать:: на гитхабе или мейлом вроде этого?
(К примеру - занятно бы бы иметь в интерфейсе бродкастов кнопку перехода к соответствующей карте)
Успехов.

**Comment by Pmmlabs** [comment]
Письмо с почты превращается в тот же самый коммент на гитхабе. Новые фичи можно предлагать в разделе issues https://github.com/Pmmlabs/OpenPeriscope/issues , их будут видеть все, и каждый сможет их реализовать раньше меня, и предложить мне свой код через pull request.
