### ISSUE TITLE
Зависание и автозакрытие программы сразу после добавления в запись трансляции

### ISSUE THREAD

**Issue by Copelaw** [Pmmlabs/OpenPeriscope#93]
Проблема не имела места примерно до 2 часов по МСК 01.07.2017. Переустановка, на другом жёстком диске, разные версии ffmpeg.exe - ничего не помогло. Использую standalone приложение версии 1.7. ОС Win 10 x64. Что делать?

НА ВЕРСИИ 1.6 ТАКОЙ ПРОБЛЕМЫ НЕТ!

**Comment by Pmmlabs** [comment]
Только что проверил, и повтор, и прямую трансляцию, всё работает
