### ISSUE TITLE
Возможно ли отключение автосоздания папок с именем пользователя

### ISSUE THREAD

**Issue by sokol001** [Pmmlabs/OpenPeriscope#97]
Проюзал OpenPeriscope v1.8 на первый взгляд более стабильное скачивание чем в v1.7
Но для меня не подходит по причине автосоздания папок с именем пользователя.
Возможно ли отключение автосоздания папок с именем пользователя.
Если да,то как это сделать.

**Comment by Pmmlabs** [comment]
Не возможно, все просили сделать подпапки, потому что это удобнее. Настройки для этого пока что нет.

**Comment by sokol001** [comment]
Нда...тогда посижу на v1.7
Возможно кому-то это удобно, мне эта фикча только усложняет жизнь,
Открывать и просмотривать что в 3К папках как то не с руки (с групп набрасываю много мусора и рекламы)

А за годную прогу Большое спасибо.

**Comment by Pmmlabs** [comment]
Запусти поиск с пустым запросом по корневой папке, и тебе покажутся все файлы из всех папок.
